spring:
  jpa:    show-sql: true
    open-in-view: false
    generate-ddl: true  # ddl-auto 기능 사용여부
    hibernate:
      ddl-auto: update  # create : 기존테이블 다 날리고 다시 시작, create-drop : 종료시점에 테이블 삭제, update : jpa변경분만 적용, validate : 엔티티와 테이블 정상 매핑 검증, none : 아무것도 안함
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true  #주석 표시        
#        dialect: org.hibernate.dialect.MariaDBDialect  
        type:
          descriptor:
            sql: trace  # parameter 값표시 로그 확인   
